name: Test
on: [push, pull_request]
jobs:
  all:
    runs-on: ${{ matrix.os }}
    env:
      RUSTFLAGS: --deny warnings
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, beta]
    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run tests
      run: |
        cargo test --verbose --workspace
    - name: Run client example
      run: |
        cargo run --example client
